import { AuditReport, Finding } from "../schemas/audit.js";

export function renderMarkdownReport(report: AuditReport): string {
  const lines: string[] = [];
  lines.push(`# Website Design Review: ${new URL(report.config.url).hostname}`);
  lines.push("");
  lines.push(`Generated: ${report.generatedAt}`);
  lines.push(`Mode: ${report.config.mode}`);
  lines.push(`Website type: ${report.websiteType} (${report.websiteTypeConfidence} confidence)`);
  lines.push("");

  lines.push("## Executive Summary");
  lines.push("");
  lines.push(`Overall score: **${report.scorecard.overallScore}/100**`);
  if (report.findings.length > 0) {
    lines.push(`The audit found ${report.findings.length} validated finding(s). The highest priority risks are:`);
    for (const finding of report.findings.slice(0, 5)) {
      lines.push(`- ${finding.title} (${finding.severity}, priority ${finding.priorityScore})`);
    }
  } else {
    lines.push("No validated findings were generated by the MVP rules. Review captured evidence manually before treating this as a clean audit.");
  }
  lines.push("");

  lines.push("## Scorecard");
  lines.push("");
  lines.push("| Dimension | Score | Confidence |");
  lines.push("| --- | ---: | --- |");
  for (const [label, item] of Object.entries(report.scorecard.subscores)) {
    lines.push(`| ${formatScoreLabel(label)} | ${item.score} | ${item.confidence} |`);
  }
  lines.push("");

  lines.push("## Top Prioritized Findings");
  lines.push("");
  for (const finding of report.findings.slice(0, 10)) {
    lines.push(renderFinding(finding));
  }

  lines.push("## Quick Wins");
  lines.push("");
  if (report.quickWins.length === 0) {
    lines.push("No high-confidence low-effort quick wins were detected.");
  } else {
    for (const finding of report.quickWins) {
      lines.push(`- **${finding.title}**: ${finding.recommendation}`);
    }
  }
  lines.push("");

  lines.push("## Page Inventory");
  lines.push("");
  lines.push("| Page | Type | Importance | Title |");
  lines.push("| --- | --- | --- | --- |");
  for (const page of report.pages) {
    lines.push(`| ${page.url} | ${page.pageType} | ${page.businessImportance} | ${page.title ?? ""} |`);
  }
  lines.push("");

  lines.push("## Redesign Briefing");
  lines.push("");
  for (const section of report.redesignBriefing) {
    lines.push(`### ${section.title}`);
    lines.push(section.body);
    lines.push("");
  }

  lines.push("## Ticket-Ready Recommendations");
  lines.push("");
  for (const ticket of report.tickets) {
    lines.push(`### ${ticket.title}`);
    lines.push(`Priority: ${ticket.priority}`);
    lines.push(`Owner: ${ticket.role.join(", ")}`);
    lines.push(`Effort: ${ticket.effort}`);
    lines.push("");
    lines.push(`Problem: ${ticket.problem}`);
    lines.push("");
    lines.push(`Goal: ${ticket.goal}`);
    lines.push("");
    lines.push("Acceptance criteria:");
    for (const criterion of ticket.acceptanceCriteria) {
      lines.push(`- ${criterion}`);
    }
    lines.push("");
  }

  lines.push("## Evidence Appendix");
  lines.push("");
  for (const page of report.pages) {
    lines.push(`### ${page.url}`);
    lines.push(`Screenshots: ${Object.values(page.screenshots).map((screenshot) => screenshot.path).join(", ")}`);
    lines.push(`Headings: ${page.text.headings.map((heading) => heading.text).slice(0, 8).join(" | ")}`);
    lines.push("");
  }

  lines.push("## Assumptions And Limitations");
  lines.push("");
  for (const assumption of report.assumptions) {
    lines.push(`- ${assumption}`);
  }
  for (const limitation of report.limitations) {
    lines.push(`- ${limitation}`);
  }
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function renderFinding(finding: Finding): string {
  return [
    `### [${finding.severity.toUpperCase()}] ${finding.title}`,
    `**Page:** ${finding.evidence.url}`,
    `**Viewport:** ${finding.evidence.viewport ?? "not viewport-specific"}`,
    `**Section:** ${finding.evidence.section ?? "unspecified"}`,
    `**Category:** ${finding.category}`,
    `**Impact:** ${finding.impact}`,
    `**Effort:** ${finding.effort}`,
    `**Confidence:** ${finding.confidence}`,
    `**Priority:** ${finding.priorityScore}`,
    `**Evidence:** ${finding.evidence.screenshotRefs.join(", ") || finding.evidence.pageId}`,
    "",
    `**Observation:** ${finding.observation}`,
    "",
    `**Why it matters:** ${finding.whyItMatters}`,
    "",
    `**Recommendation:** ${finding.recommendation}`,
    "",
    "**Acceptance criteria:**",
    ...finding.implementation.acceptanceCriteria.map((criterion) => `- ${criterion}`),
    ""
  ].join("\n");
}

function formatScoreLabel(value: string): string {
  return value.replace(/([A-Z])/g, " $1").replace(/^./, (char) => char.toUpperCase());
}
