import { readFile } from "node:fs/promises";
import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { chromium } from "playwright";
import { AgentVisualReview, AuditReport } from "../schemas/audit.js";
import { readReportFromAuditDir } from "../storage/index.js";
import { AuditPaths, createNestedAuditPaths } from "../storage/project.js";
import { ensureDir, writeJson, writeText } from "../utils/fs.js";
import { buildScreenshotManifest, ScreenshotManifest, writeScreenshotManifest } from "./screenshot-manifest.js";

export type ReviewPackResult = {
  auditId: string;
  auditRoot: string;
  packRoot: string;
  screenshotManifest: string;
  template: string;
  schema: string;
  instructions: string;
  contactSheets: string[];
  pagePrompts: string[];
};

export async function buildReviewPack(auditDir: string): Promise<ReviewPackResult> {
  const report = await readReportFromAuditDir(auditDir);
  const paths = await createNestedAuditPaths(auditDir);
  const packRoot = path.join(paths.report, "agent-review-pack");
  const promptRoot = path.join(packRoot, "page-prompts");
  const contactSheetRoot = path.join(paths.report, "contact-sheets");
  await ensureDir(packRoot);
  await ensureDir(promptRoot);
  await ensureDir(contactSheetRoot);

  const manifest = await writeScreenshotManifest(report, paths);
  await writeJson(path.join(packRoot, "screenshot-manifest.json"), manifest);
  await writeJson(path.join(packRoot, "agent-review-template.json"), reviewTemplate(report, manifest));
  await writeJson(path.join(packRoot, "agent-review.schema.json"), agentReviewJsonSchema());
  await writeText(path.join(packRoot, "README.md"), renderReviewPackReadme(report, paths));

  const pagePrompts = await writePagePrompts(report, manifest, promptRoot);
  const contactSheets = await renderContactSheets(report, paths, manifest, contactSheetRoot);

  return {
    auditId: report.auditId,
    auditRoot: paths.auditRoot,
    packRoot,
    screenshotManifest: path.join(paths.report, "screenshot-manifest.json"),
    template: path.join(packRoot, "agent-review-template.json"),
    schema: path.join(packRoot, "agent-review.schema.json"),
    instructions: path.join(packRoot, "README.md"),
    contactSheets,
    pagePrompts
  };
}

function reviewTemplate(report: AuditReport, manifest: ScreenshotManifest): AgentVisualReview {
  return {
    schemaVersion: "design-review-workflow.agent-visual-review.v1",
    reviewer: "agent-name",
    reviewedAt: new Date().toISOString(),
    auditId: report.auditId,
    screenshotsReviewed: manifest.screenshots.map((screenshot) => screenshot.id),
    pageReviews: report.pages.map((page) => ({
      pageId: page.pageId,
      url: page.url,
      screenshotsReviewed: Object.keys(page.screenshots),
      firstViewport: "TODO: inspect the first viewport screenshot and describe visual hierarchy, clarity, and immediate comprehension.",
      hierarchy: "TODO: inspect page hierarchy, typography, spacing, rhythm, scannability, and whether the most important content leads.",
      navigation: "TODO: inspect navigation clarity, orientation, information scent, and whether page-to-page movement is obvious.",
      mobile: "TODO: inspect mobile composition, cropping, density, CTA placement, and whether important content survives the small viewport.",
      trustAndProof: "TODO: inspect trust signals, proof, portfolio/service credibility, reassurance, and whether claims are visually supported.",
      notes: []
    })),
    visualFindings: [],
    strengths: [],
    risks: [],
    confidence: "medium",
    limitations: ["Template generated by the workflow. Replace TODO fields after visually inspecting screenshots."]
  };
}

function agentReviewJsonSchema() {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "AgentVisualReview",
    type: "object",
    required: ["schemaVersion", "reviewer", "reviewedAt", "auditId", "screenshotsReviewed", "pageReviews", "visualFindings", "strengths", "risks", "confidence", "limitations"],
    additionalProperties: false,
    properties: {
      schemaVersion: { const: "design-review-workflow.agent-visual-review.v1" },
      reviewer: { type: "string", minLength: 1 },
      reviewedAt: { type: "string", minLength: 1 },
      auditId: { type: "string", minLength: 1 },
      screenshotsReviewed: { type: "array", minItems: 1, items: { type: "string", minLength: 1 } },
      pageReviews: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          required: ["pageId", "url", "screenshotsReviewed", "firstViewport", "hierarchy", "navigation", "mobile", "trustAndProof", "notes"],
          additionalProperties: false,
          properties: {
            pageId: { type: "string", minLength: 1 },
            url: { type: "string", format: "uri" },
            screenshotsReviewed: { type: "array", minItems: 1, items: { type: "string", minLength: 1 } },
            firstViewport: { type: "string", minLength: 20 },
            hierarchy: { type: "string", minLength: 20 },
            navigation: { type: "string", minLength: 20 },
            mobile: { type: "string", minLength: 20 },
            trustAndProof: { type: "string", minLength: 20 },
            notes: { type: "array", items: { type: "string" } }
          }
        }
      },
      visualFindings: {
        type: "array",
        items: {
          type: "object",
          required: [
            "reviewId",
            "title",
            "category",
            "severity",
            "impact",
            "effort",
            "confidence",
            "pageId",
            "url",
            "evidenceRefs",
            "observation",
            "whyItMatters",
            "recommendation",
            "acceptanceCriteria",
            "sourceFindingIds"
          ],
          additionalProperties: false,
          properties: {
            reviewId: { type: "string", minLength: 1 },
            title: { type: "string", minLength: 1 },
            category: { enum: ["visual_design", "ux", "conversion", "mobile", "brand", "trust", "content_design", "accessibility_basic", "performance_perception", "design_system", "competitor_gap"] },
            severity: { enum: ["critical", "high", "medium", "low"] },
            impact: { enum: ["high", "medium", "low"] },
            effort: { enum: ["low", "medium", "high"] },
            confidence: { enum: ["high", "medium", "low"] },
            pageId: { type: "string", minLength: 1 },
            url: { type: "string", format: "uri" },
            section: { type: "string" },
            evidenceRefs: { type: "array", minItems: 1, items: { type: "string", minLength: 1 } },
            observation: { type: "string", minLength: 20 },
            whyItMatters: { type: "string", minLength: 20 },
            recommendation: { type: "string", minLength: 20 },
            acceptanceCriteria: { type: "array", minItems: 1, items: { type: "string", minLength: 8 } },
            sourceFindingIds: { type: "array", items: { type: "string" } }
          }
        }
      },
      strengths: { type: "array", items: { type: "string" } },
      risks: { type: "array", items: { type: "string" } },
      confidence: { enum: ["high", "medium", "low"] },
      limitations: { type: "array", items: { type: "string" } }
    }
  };
}

function renderReviewPackReadme(report: AuditReport, paths: AuditPaths): string {
  return `# Agent Visual Review Pack

Target: ${report.config.url}
Audit: ${report.auditId}

This pack is for the repo-capable multimodal agent running the workflow. It intentionally does not call any model API. Inspect the screenshots and evidence yourself, then write a completed review JSON.

## Required Steps

1. Open \`../screenshot-manifest.json\` and the PNG files in \`../contact-sheets/\`.
2. Inspect desktop and mobile screenshots for each captured page.
3. Use \`agent-review-template.json\` as the starting shape.
4. Replace every TODO with concrete visual observations based on screenshots.
5. Save your completed artifact at \`agent-runs/<agent>/visual-review.json\` or another local path.
6. Import it:

\`\`\`bash
node apps/cli/dist/index.js agent-review import --report ${paths.auditRoot} --file agent-runs/<agent>/visual-review.json
node apps/cli/dist/index.js business-grade lint --report ${paths.auditRoot}
\`\`\`

## Review Rules

- Reference only screenshot IDs or screenshot paths listed in \`screenshot-manifest.json\`.
- Do not claim analytics, heatmaps, users, revenue, competitor performance, or brand rules unless they are explicitly supplied as evidence.
- Prefer grouped, root-cause issues over repeated page-level symptoms.
- Cover hierarchy, first viewport, CTA clarity, trust/proof, portfolio narrative or service persuasion, bilingual consistency when visible, mobile composition, visual-system coherence, and accessibility basics.
- If confidence is low, say why in \`limitations\`.
`;
}

async function writePagePrompts(report: AuditReport, manifest: ScreenshotManifest, promptRoot: string): Promise<string[]> {
  const output: string[] = [];
  for (const page of report.pages) {
    const screenshots = manifest.screenshots.filter((screenshot) => screenshot.pageId === page.pageId);
    const filePath = path.join(promptRoot, `${page.pageId}.md`);
    await writeText(
      filePath,
      [
        `# Visual Review Prompt: ${page.title ?? page.url}`,
        "",
        `Page ID: ${page.pageId}`,
        `URL: ${page.url}`,
        `Page type: ${page.pageType}`,
        `Importance: ${page.businessImportance}`,
        "",
        "## Screenshots To Inspect",
        "",
        ...screenshots.map((screenshot) => `- ${screenshot.id}: ${screenshot.path} (${screenshot.viewport}, ${screenshot.kind}, ${screenshot.width}x${screenshot.height})`),
        "",
        "## Required Judgment",
        "",
        "- First viewport: does the page immediately communicate what it is, who it is for, and what to do next?",
        "- Hierarchy: do typography, spacing, contrast, and layout make the important content dominant?",
        "- CTA clarity: is the primary next action visually and verbally clear?",
        "- Trust/proof: are credibility signals present, specific, and close to decision points?",
        "- Mobile composition: does the small viewport preserve the intent without awkward cropping or excessive density?",
        "- Visual-system coherence: do colors, type, spacing, components, imagery, and interaction states feel consistent?",
        "",
        "Write findings only when the screenshot evidence supports the claim.",
        ""
      ].join("\n")
    );
    output.push(filePath);
  }
  return output;
}

async function renderContactSheets(report: AuditReport, paths: AuditPaths, manifest: ScreenshotManifest, contactSheetRoot: string): Promise<string[]> {
  const browser = await chromium.launch();
  try {
    const output: string[] = [];
    const allPath = path.join(contactSheetRoot, "all-pages.png");
    await renderContactSheet(browser, allPath, "All Captured Screenshots", manifest.screenshots);
    output.push(allPath);

    for (const page of report.pages) {
      const screenshots = manifest.screenshots.filter((screenshot) => screenshot.pageId === page.pageId);
      if (screenshots.length === 0) continue;
      const sheetPath = path.join(contactSheetRoot, `${page.pageId}.png`);
      await renderContactSheet(browser, sheetPath, page.title ?? page.url, screenshots);
      output.push(sheetPath);
    }
    await writeText(path.join(contactSheetRoot, "index.html"), await renderContactSheetHtml("All Captured Screenshots", manifest.screenshots));
    await writeJson(path.join(paths.report, "agent-review-pack", "contact-sheets.json"), {
      schemaVersion: "design-review-workflow.contact-sheets.v1",
      auditId: report.auditId,
      generatedAt: new Date().toISOString(),
      sheets: output
    });
    return output;
  } finally {
    await browser.close();
  }
}

async function renderContactSheet(browser: Awaited<ReturnType<typeof chromium.launch>>, outputPath: string, title: string, screenshots: ScreenshotManifest["screenshots"]): Promise<void> {
  const page = await browser.newPage({ viewport: { width: 1600, height: 1200 }, deviceScaleFactor: 1 });
  await page.setContent(await renderContactSheetHtml(title, screenshots), { waitUntil: "networkidle" });
  await page.screenshot({ path: outputPath, fullPage: true });
  await page.close();
}

async function renderContactSheetHtml(title: string, screenshots: ScreenshotManifest["screenshots"]): Promise<string> {
  const rows = await Promise.all(
    screenshots.map(async (screenshot) => {
      const src = await screenshotSrc(screenshot.absolutePath);
      return `<figure>
        <img src="${escapeAttribute(src)}" alt="${escapeAttribute(screenshot.id)}" />
        <figcaption><strong>${escapeHtml(screenshot.id)}</strong><br />${escapeHtml(screenshot.url)}<br />${escapeHtml(screenshot.viewport)} / ${escapeHtml(screenshot.kind)} / ${screenshot.width}x${screenshot.height}</figcaption>
      </figure>`;
    })
  );
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light; --ink:#172026; --muted:#61717b; --line:#d8e2e0; --panel:#f6faf8; --accent:#0f766e; }
    body { margin:0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color:var(--ink); background:#fff; }
    main { padding:28px; }
    h1 { margin:0 0 18px; font-size:28px; }
    .grid { display:grid; grid-template-columns:repeat(2, minmax(0, 1fr)); gap:18px; align-items:start; }
    figure { margin:0; border:1px solid var(--line); border-radius:8px; background:var(--panel); overflow:hidden; }
    img { display:block; width:100%; height:auto; background:#fff; }
    figcaption { padding:10px 12px; color:var(--muted); font-size:13px; }
    strong { color:var(--ink); }
  </style>
</head>
<body>
  <main>
    <h1>${escapeHtml(title)}</h1>
    <section class="grid">
      ${rows.join("")}
    </section>
  </main>
</body>
</html>`;
}

async function screenshotSrc(filePath: string): Promise<string> {
  try {
    const data = await readFile(filePath);
    return `data:image/png;base64,${data.toString("base64")}`;
  } catch {
    return pathToFileURL(filePath).href;
  }
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char] ?? char);
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replace(/`/g, "&#096;");
}
